name: XCS234
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - notebook=7.4.4
  - tk=8.6.14
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - tensorboard=2.19.0
  - pip=25.0
  - pip:
    - setuptools==80.9.0
    - cmake==4.0.3; sys_platform != "win32"
    - wget==3.2; sys_platform != "win32"
    - matplotlib==3.10.5
    - tqdm==4.67.1
    - numpy==2.2.6
    - pandas==2.3.1
    - scipy==1.16.1
    - pyglet==2.1.6
    - gymnasium[mujoco]==1.2.0
    - stable_baselines3[extra]==2.7.0
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.7.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.7.1+cpu; sys_platform == "linux" or sys_platform == "win32"
